In [1]:
pip install mlxtend

Collecting mlxtendNote: you may need to restart the kernel to use updated packages.

  Downloading mlxtend-0.23.3-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (1.14.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (2.1.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.3-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------ --------------------------------- 0.2/1.4 MB 4.6 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.4 MB 4.6 MB/s eta 0:00:01
   ------------------ --------------------- 0.6/1.4 MB 4.9 MB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.4 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 1.2/1.4 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 5.0 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.3

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

import warnings
warnings.filterwarnings("ignore")

In [3]:
data= {
    "Transaction": [1,2,3,4,5,6,7,8,9,10],
    "Bread": [1,1,0,1,0,1,0,1,0,1],
    "Butter": [1,0,1,0,1,1,0,1,0,1],
    "Milk": [1,0,1,1,0,0,1,0,1,1],
    "Egg": [0,1,0,1,1,0,0,0,1,0],
    "Jam": [0,1,1,0,1,0,1,1,0,0]
}

In [4]:
df= pd.DataFrame(data).set_index("Transaction")

In [5]:
df

             Bread  Butter  Milk  Egg  Jam
Transaction
1                1       1     1    0    0
2                1       0     0    1    1
3                0       1     1    0    1
4                1       0     1    1    0
5                0       1     0    1    1
6                1       1     0    0    0
7                0       0     1    0    1
8                1       1     0    0    1
9                0       0     1    1    0
10               1       1     1    0    0

In [6]:
freq_itemset= apriori(df,min_support=0.3, use_colnames=True)

In [7]:
freq_itemset

   support         itemsets
0      0.6          (Bread)
1      0.6         (Butter)
2      0.6           (Milk)
3      0.4            (Egg)
4      0.5            (Jam)
5      0.4  (Bread, Butter)
6      0.3    (Bread, Milk)
7      0.3   (Butter, Milk)
8      0.3    (Jam, Butter)

In [15]:
rules= association_rules(freq_itemset, metric="confidence", min_threshold=0.5, num_itemsets=5)

In [16]:
rules.iloc[:, :7]

  antecedents consequents  antecedent support  consequent support  support  confidence      lift
0     (Bread)    (Butter)                 0.6                 0.6      0.4    0.666667  1.111111
1    (Butter)     (Bread)                 0.6                 0.6      0.4    0.666667  1.111111
2     (Bread)      (Milk)                 0.6                 0.6      0.3    0.500000  0.833333
3      (Milk)     (Bread)                 0.6                 0.6      0.3    0.500000  0.833333
4    (Butter)      (Milk)                 0.6                 0.6      0.3    0.500000  0.833333
5      (Milk)    (Butter)                 0.6                 0.6      0.3    0.500000  0.833333
6       (Jam)    (Butter)                 0.5                 0.6      0.3    0.600000  1.000000
7    (Butter)       (Jam)                 0.6                 0.5      0.3    0.500000  1.000000